
package ru.test.wscli.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWsImpl", targetNamespace = "http://ws.test.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWsImpl {


    /**
     * 
     * @param book
     * @return
     *     returns ru.test.ws.Library
     */
    @WebMethod
    @WebResult(name = "DoSmthResp", partName = "DoSmthResp")
    public Library doSmth(
        @WebParam(name = "Book", partName = "Book")
        Book book);

    /**
     * 
     * @param yourName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "SayHellResp", partName = "SayHellResp")
    public String sayHello(
        @WebParam(name = "YourName", partName = "YourName")
        String yourName);

}
