
package ru.itpark.graduate.pb.web.clnt.genapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PbWs", targetNamespace = "http://ws.pb.graduate.itpark.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PbWs {


    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "PhoneBookExecuteCheckAuthPairResponse", partName = "PhoneBookExecuteCheckAuthPairResponse")
    public boolean phoneBookExecuteCheckAuthPair(
        @WebParam(name = "Login", partName = "Login")
        String login,
        @WebParam(name = "Password", partName = "Password")
        String password);

    /**
     * 
     * @param phoneBookRecordCreateRequest
     * @return
     *     returns ru.itpark.graduate.pb.ws.TPhoneBookRecordCreateRes
     */
    @WebMethod
    @WebResult(name = "PhoneBookRecordCreateResponse", partName = "PhoneBookRecordCreateResponse")
    public TPhoneBookRecordCreateRes phoneBookRecordCreate(
        @WebParam(name = "PhoneBookRecordCreateRequest", partName = "PhoneBookRecordCreateRequest")
        TPhoneBookRecordCreateReq phoneBookRecordCreateRequest);

    /**
     * 
     * @param phoneBookRecordGetListRequest
     * @return
     *     returns ru.itpark.graduate.pb.ws.TPhoneBookRecordGetListRes
     */
    @WebMethod
    @WebResult(name = "PhoneBookRecordGetListResponse", partName = "PhoneBookRecordGetListResponse")
    public TPhoneBookRecordGetListRes phoneBookRecordGetList(
        @WebParam(name = "PhoneBookRecordGetListRequest", partName = "PhoneBookRecordGetListRequest")
        TPhoneBookRecordGetListReq phoneBookRecordGetListRequest);

    /**
     * 
     * @param phoneBookRecordUpdateRequest
     * @return
     *     returns ru.itpark.graduate.pb.ws.TPhoneBookRecordUpdateRes
     */
    @WebMethod
    @WebResult(name = "PhoneBookRecordUpdateResponse", partName = "PhoneBookRecordUpdateResponse")
    public TPhoneBookRecordUpdateRes phoneBookRecordUpdate(
        @WebParam(name = "PhoneBookRecordUpdateRequest", partName = "PhoneBookRecordUpdateRequest")
        TPhoneBookRecordUpdateReq phoneBookRecordUpdateRequest);

    /**
     * 
     * @param phoneBookRecordDeleteRequest
     * @return
     *     returns ru.itpark.graduate.pb.ws.TPhoneBookRecordDeleteRes
     */
    @WebMethod
    @WebResult(name = "PhoneBookRecordDeleteResponse", partName = "PhoneBookRecordDeleteResponse")
    public TPhoneBookRecordDeleteRes phoneBookRecordDelete(
        @WebParam(name = "PhoneBookRecordDeleteRequest", partName = "PhoneBookRecordDeleteRequest")
        TPhoneBookRecordDeleteReq phoneBookRecordDeleteRequest);

}
